// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGQFzy_zG47pAIxZQDGEcfCSYq4d7XGY',
    appId: '1:544981007133:web:0a539591aaa13d74677ff4',
    messagingSenderId: '544981007133',
    projectId: 'skriftes-qa',
    authDomain: 'skriftes-qa.firebaseapp.com',
    storageBucket: 'skriftes-qa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzScQwhzyK6sCqX1diG3uqwAdj_R26RS8',
    appId: '1:544981007133:android:325a13b9eeae11d7677ff4',
    messagingSenderId: '544981007133',
    projectId: 'skriftes-qa',
    storageBucket: 'skriftes-qa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWAz-7og43IDTipk_WK1H_QO3bFD9QXWY',
    appId: '1:544981007133:ios:bb93267da842d9b5677ff4',
    messagingSenderId: '544981007133',
    projectId: 'skriftes-qa',
    storageBucket: 'skriftes-qa.appspot.com',
    iosBundleId: 'com.example.skriftesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWAz-7og43IDTipk_WK1H_QO3bFD9QXWY',
    appId: '1:544981007133:ios:bb93267da842d9b5677ff4',
    messagingSenderId: '544981007133',
    projectId: 'skriftes-qa',
    storageBucket: 'skriftes-qa.appspot.com',
    iosBundleId: 'com.example.skriftesProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAGQFzy_zG47pAIxZQDGEcfCSYq4d7XGY',
    appId: '1:544981007133:web:7df46c77cb128fbb677ff4',
    messagingSenderId: '544981007133',
    projectId: 'skriftes-qa',
    authDomain: 'skriftes-qa.firebaseapp.com',
    storageBucket: 'skriftes-qa.appspot.com',
  );
}
